version: "3.7"
services:
  db:
    image: 'bitnami/mariadb:10.4'
    ports:
      - '3306:3306'
    volumes:
      - 'mariadb-data:/bitnami'
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${CONFIG_DB_SQL_SCRIPT}:/docker-entrypoint-initdb.d:ro"
      #- "../sql/config/my.cnf:/etc/mysql/my.cnf"
    environment:
      - MARIADB_REPLICATION_MODE=master
      - BITNAMI_DEBUG=true
      - MARIADB_REPLICATION_USER=repl_user
      - MARIADB_USER=${CONFIG_DB_USER}
      - MARIADB_PASSWORD=${CONFIG_DB_USER}
      - MARIADB_DATABASE=${CONFIG_DB_DATABASE}
      - MARIADB_REPLICATION_PASSWORD=${CONFIG_DB_ROOT_PASSWORD}
      - ALLOW_EMPTY_PASSWORD=no
      - MARIADB_ROOT_PASSWORD=${CONFIG_DB_ROOT_PASSWORD}
      - MARIADB_EXTRA_FLAGS=--wait_timeout=28800 --innodb_log_file_size=128MB --max_allowed_packet=128MB
    networks:
      - api
    labels:
      - "traefik.enable=false"
  db-slave:
    image: 'bitnami/mariadb:10.4'
    depends_on:
      - db
    environment:
      - MYSQL_ROOT_HOST=${CONFIG_DB_ROOT_HOST}
      - MARIADB_REPLICATION_MODE=slave
      - MARIADB_REPLICATION_USER=repl_user
      - MARIADB_USER=${CONFIG_DB_USER}
      - MARIADB_PASSWORD=${CONFIG_DB_USER}
      - MARIADB_DATABASE=${CONFIG_DB_DATABASE}
      - MARIADB_MASTER_HOST=mariadb-master
      - MARIADB_MASTER_PORT_NUMBER=3306
      - MARIADB_MASTER_ROOT_PASSWORD=${CONFIG_DB_ROOT_PASSWORD}
      - ALLOW_EMPTY_PASSWORD=no
      - MARIADB_REPLICATION_PASSWORD=${CONFIG_DB_ROOT_PASSWORD}
      - MARIADB_EXTRA_FLAGS=--wait_timeout=28800 --innodb_log_file_size=128MB --max_allowed_packet=128MB
    networks:
      - api
    labels:
      - "traefik.enable=false"
  adminer:
    image: adminer
    ports:
      - "8085:8080"
    environment:
      - ADMINER_DEFAULT_DB_DRIVER=mysql
      - ADMINER_DEFAULT_DB_HOST=${CONFIG_DB_CONNECTOR}
      - ADMINER_DEFAULT_DB_NAME=${CONFIG_DB_DATABASE}
    networks:
      - api
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    labels:
      - "traefik.enable=false"
  rethinkdb:
    image: rethinkdb:custom
    build: ${CONFIG_NOSQL_BUILD_PATH}
    ports:
     - "28015"
     - "8080"
    networks:
      - api
    volumes:
     - ${CONFIG_NOSQL_TOOLS_DATA_PATH}:/data
    command: rethinkdb -d /data --bind all
  rethinkdb-tools:
    image: rethinkdb-tools:custom
    build: ${CONFIG_NOSQL_BUILD_PATH}
    volumes:
     - ${CONFIG_NOSQL_TOOLS_DATA_PATH}:/data
    networks:
      - api
    command: rethinkdb import -f /data/data.json --table data.table --format json -c rethinkdb:28015
  mongo:
    image: mongo:latest
    expose:
      - "27017"
    networks:
      - api
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    labels:
      - "traefik.enable=false"

volumes:
  mariadb-data:
    driver: local
